import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import '../sass/index.scss';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IT-Аутсорсинг компания Udevs - IT консалтинг, разработка и внедрение ERP систем, разработка мобильных приложений, UI / UX дизайн, оптимизация инфраструктуры",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
